countryDataWant = {
    "AQ": 10,
    "JP": 20,
    "EG": 7,
    "BE": 11,
    "DE": 15,
    "BS": 5,
    "MY": 7,
    "BR": 10,
    "IT": 13,
    "US": 10,
    "FI": 4,
    "ID": 8,
    "MW": 4,
    "DK": 8,
    "KR": 14,
    "AT": 8,
    "AZ": 5,
    "AL": 5,
    "FJ": 8,
    "FR": 9,
    "AR": 5,
    "NL": 7,
    "JM": 4,
    "CN": 9,
    "SG": 5,
    "CA": 6,
    "GR": 11,
    "SK": 3,
    "FL": 8,
    "BT": 5,
    "DZ": 4,
    "CN": 4,
    "AS": 5,
    "CZ": 6,
    "PH": 6,
    "GB": 9,
    "CF": 3,
    "NZ": 11,
    "NC": 4,
    "KZ": 3,
    "TH": 8,
    "HR": 4,
    "CV": 3,
    "CY": 7,
    "AD": 5,
    "PL": 11,
    "CR": 5,
    "CH": 14,
    "CU": 5,
    "SE": 12,
    "CO": 4,
    "PG": 5,
    "IS": 9,
    "AO": 5,
    "KH": 3,
    "ZA": 5,
    "TW": 7,
    "NO": 10,
    "AI": 5,
    "GF": 3,
    "MG": 5,
    "CK": 3,
    "MV": 8,
    "GL": 5,
    "PF": 3,
    "MN": 5,
    "HU": 4,
    "ES": 9,
    "VN": 7,
    "AG": 5,
    "EE": 3,
    "SA": 4,
    "KP": 2,
    "IR": 3,
    "LI": 3,
    "PS": 4,
    "PA": 3,
    "ET": 3,
    "SV": 3,
    "GE": 3,
    "MC": 3,
    "VA": 4,
    "AE": 4,
    "MX": 5,
    "NA": 3,
    "RU": 7,
    "PT": 6,
    "IN": 4,
    "NP": 5,
    "RO": 5,
    "IE": 4,
    "BH": 3,
    "BD": 3,
    "LU": 3,
    "NG": 3,
    "TO": 3,
    "BB": 3,
    "SL": 3,
    "VU": 3,
    "BY": 3,
    "PW": 3,
    "ZW": 3,
    "BZ": 3,
    "BJ": 3,
    "PE": 4,
    "BO": 3,
    "LA": 3,
    "BA": 3,
    "MK": 3,
    "BW": 3,
    "VG": 3,
    "MA": 4,
    "BG": 2,
    "TR": 3,
    "UA": 4,
    "JO": 3,
    "SJ": 3
}

$(function() {
    $('#map_world_want').vectorMap({
        map: 'world_merc',
        backgroundColor: "#fbfbfe",
        zoomOnScroll: true,
        regionStyle: {
            initial: {
                "fill-opacity": 1,
                "stroke": '#050315',
                "stroke-width": 0.5
            },
            hover: {
                "fill-opacity": 0.8,
                "cursor": 'pointer'
            },
            selected: {
                "fill": '#050315'
            }
        },
        series: {
            regions: [{
                values: countryData,
                scale: ["#a9a6ff", "#3351d7"],
                normalizeFunction: "polynomial"
            }]
        },
        onRegionTipShow: function(e, el, code){
            el.html(el.html() + ' (Visitors - ' + countryDataWant[code] + ')');
        }
    });
})
